name: hyfluid_
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.11.17=hbcca054_0
  - ffmpeg=4.2.2=h20bf706_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.6.15=he1e5248_0
  - lame=3.100=h7f98852_1001
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.4=h5eee18b_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.12=h7f8727e_0
  - pip=23.3.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2023c=h04d1e81_0
  - wheel=0.41.2=py310h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - asttokens==2.4.1
    - certifi==2023.11.17
    - charset-normalizer==3.3.2
    - cmake==3.28.1
    - colorama==0.4.6
    - configargparse==1.5.3
    - cycler==0.12.1
    - decorator==5.1.1
    - dill==0.3.7
    - exceptiongroup==1.2.0
    - executing==2.0.1
    - filelock==3.13.1
    - fonttools==4.47.0
    - idna==3.6
    - imageio==2.27.0
    - imageio-ffmpeg==0.4.5
    - ipdb==0.13.13
    - ipython==8.18.1
    - jedi==0.19.1
    - jinja2==3.1.2
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - kornia==0.6.11
    - lazy-loader==0.3
    - lit==17.0.6
    - lpips==0.1.4
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mpmath==1.3.0
    - networkx==3.2.1
    - numpy==1.24.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - opencv-python==4.6.0.66
    - packaging==23.2
    - parso==0.8.3
    - pexpect==4.9.0
    - pillow==10.1.0
    - plyfile==1.0.2
    - prompt-toolkit==3.0.43
    - psutil==5.9.7
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pygments==2.17.2
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - pywavelets==1.5.0
    - requests==2.31.0
    - rich==13.7.0
    - scikit-image==0.20.0
    - scikit-learn==1.3.2
    - scipy==1.11.4
    - six==1.16.0
    - stack-data==0.6.3
    - sympy==1.12
    - taichi==1.5.0
    - threadpoolctl==3.2.0
    - tifffile==2023.12.9
    - tomli==2.0.1
    - torch==2.0.1
    - torchvision==0.15.2
    - tqdm==4.65.0
    - traitlets==5.14.0
    - triton==2.0.0
    - typing-extensions==4.9.0
    - urllib3==2.1.0
    - vtk==9.2.6
    - wcwidth==0.2.12
